/home/tzc/anaconda3/envs/transformers/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
04/01/2022 22:58:38 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 8
Process index: 0
Local process index: 0
Device: cuda:0
Use FP16 precision: False

04/01/2022 22:58:38 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 8
Process index: 1
Local process index: 1
Device: cuda:1
Use FP16 precision: False

04/01/2022 22:58:38 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 8
Process index: 3
Local process index: 3
Device: cuda:3
Use FP16 precision: False

04/01/2022 22:58:38 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 8
Process index: 6
Local process index: 6
Device: cuda:6
Use FP16 precision: False

04/01/2022 22:58:38 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 8
Process index: 4
Local process index: 4
Device: cuda:4
Use FP16 precision: False

04/01/2022 22:58:38 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 8
Process index: 7
Local process index: 7
Device: cuda:7
Use FP16 precision: False

04/01/2022 22:58:38 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 8
Process index: 5
Local process index: 5
Device: cuda:5
Use FP16 precision: False

04/01/2022 22:58:38 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 8
Process index: 2
Local process index: 2
Device: cuda:2
Use FP16 precision: False

Downloading and preparing dataset json/default to /data/tzc/huggingface/json/default-e7acfd7003f5b189/0.0.0/ac0ca5f5289a6cf108e706efcf040422dbbfa8e658dee6a819f20d76bb84d26b...
  0%|          | 0/2 [00:00<?, ?it/s]04/01/2022 22:58:56 - WARNING - datasets.builder - Using custom data configuration default-e7acfd7003f5b189
100%|██████████| 2/2 [00:00<00:00, 7194.35it/s]
  0%|          | 0/2 [00:00<?, ?it/s]100%|██████████| 2/2 [00:00<00:00, 1053.45it/s]
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2245492 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2245493 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2245494 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2245495 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2245496 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2245497 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2245498 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 2245491) of binary: /home/tzc/anaconda3/envs/transformers/bin/python
Traceback (most recent call last):
  File "/home/tzc/anaconda3/envs/transformers/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tzc/anaconda3/envs/transformers/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tzc/anaconda3/envs/transformers/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/tzc/anaconda3/envs/transformers/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/tzc/anaconda3/envs/transformers/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/tzc/anaconda3/envs/transformers/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/tzc/anaconda3/envs/transformers/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/tzc/anaconda3/envs/transformers/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
========================================================
run_mlm_no_trainier.py FAILED
--------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
--------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-04-02_01:38:07
  host      : amax
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 2245491)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 2245491
========================================================
pretrain.sh: line 24: --num_train_epochs: command not found
